#!/bin/sh
for p in cat echo forktest grep init kill ln ls malloctest mkdir rm sh stressfs ticktest usertests wc zombie ps
do
	clang -g -I../ulib/include -target x86_64-none-unknown-elf -msoft-float -fno-builtin -nostdinc -nostdlib -c -o $p.o $p.c
	ld.lld -N -Ttext 0x1000 -e main -o $p $p.o ../target/x86_64-unknown-rxv64-elf/release/libulib.a
	cp $p _$p
	llvm-strip _$p
done
../bin/mkfs ../sdahci0.img _*
